### ISSUE TITLE
Can't install rTisane

### ISSUE THREAD

**Issue by ShermanMusk** [emjun/rTisane#11]
I have tired to install rTisane for many times with following step:
install.packages("remotes")
remotes::install_github("emjun/tisaner")
But after that, I got this error.

byte-compile and prepare package for lazy loading
in method for 'assign_cardinality_from_data' with signature '"AbstractVariable","Dataset"': no definition for class "Dataset"
in method for 'calculate_cardinality_from_data' with signature '"AbstractVariable","Dataset"': no definition for class "Dataset"
Error in setClassUnion("integerORAbstractVariableORAtMostORPer", c("integer",  : 
  the member classes must be defined: not true of "AtMost", "Per"
Error: unable to load R code in package 'tisaner'
Execution halted
ERROR: lazy loading failed for package 'tisaner'
* removing 'C:/Users/Golden/AppData/Local/R/win-library/4.3/tisaner'

**Comment by ShermanMusk** [comment]
I installed latest version R 4.3.0

**Comment by elmisback** [comment]
Hi! Thanks for you interest in rTisane. Right now this is only research software, and we've only tested that it runs on our own system. We can't support running it on other systems yet. After the study, we'll handle distribution for use on other systems.

**Comment by ShermanMusk** [comment]
Okay

**Comment by ShermanMusk** [comment]
But I have to have a test what you and @emjun required in 1th June.

**Comment by elmisback** [comment]
Don't worry about it! We got plenty of material to work with already, and you will be compensated as previously discussed. Thank you again for participating in our study!

**Comment by ShermanMusk** [comment]
Awesome, thanks for the update!
